Salesforce Template Application/force-app/main/default/objects/DocuSignCredentialsSetting__c/DocuSignCredentialsSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>DocuSign Credentials Setting to store docusign user connection data</description>
    <label>DocuSign Credentials Setting</label>
</CustomObject>

Salesforce Template Application/force-app/main/default/objects/DocuSignCredentialsSetting__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

Salesforce Template Application/force-app/main/default/classes/DocusignCredentialSetting.cls
/**
 * @description       : 
 * @author            : Salesforce Consultancy
 * @group             : 
 * @last modified on  : 09-26-2022
 * @last modified by  : Salesforce Consultancy
**/
public with sharing class DocusignCredentialSetting {


    /**
     * get the Docusign Settings 
     * 
     */
    public static DocuSignCredentialsSetting__c getDocusignCredential(){
        DocuSignCredentialsSetting__c settings = null;
        Map<String,DocuSignCredentialsSetting__c> credentialSetting = DocuSignCredentialsSetting__c.getAll(); 
        for(DocuSignCredentialsSetting__c credentialIns : credentialSetting.values()){ 
    
            if (credentialIns.isActive__C ){
                settings =  credentialIns;
            }
        }
        return settings ;
    }
}